test_that("Professions table is returned appropriately for each legislature", {
  skip_on_cran()
  expect_identical(class(get_profession("aut")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_profession("can")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_profession("cze")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_profession("esp")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_profession("fra")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_profession("deu")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_profession("irl")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_profession("sco")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_profession("gbr")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_profession("usa_house")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_profession("usa_senate")), "data.frame")
  Sys.sleep(1)

  expect_true(all(dim(get_profession("aut")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_profession("can")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_profession("cze")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_profession("esp")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_profession("fra")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_profession("deu")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_profession("irl")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_profession("sco")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_profession("gbr")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_profession("usa_house")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_profession("usa_senate")) > 0))
  Sys.sleep(1)

  expect_identical(colnames(get_profession("aut"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_profession("can"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_profession("cze"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_profession("esp"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_profession("fra"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_profession("deu"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_profession("irl"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_profession("sco"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_profession("gbr"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_profession("usa_house"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_profession("usa_senate"))[1], c("wikidataid"))
  Sys.sleep(1)
})
