test_that("Core table is returned appropriately for each legislature", {
  skip_on_cran()
  expect_identical(class(get_core("aut")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_core("can")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_core("cze")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_core("esp")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_core("fra")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_core("deu")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_core("irl")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_core("sco")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_core("gbr")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_core("usa_house")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_core("usa_senate")), "data.frame")
  Sys.sleep(1)

  expect_true(all(dim(get_core("aut")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_core("can")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_core("cze")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_core("esp")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_core("fra")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_core("deu")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_core("irl")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_core("sco")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_core("gbr")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_core("usa_house")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_core("usa_senate")) > 0))
  Sys.sleep(1)

  expect_identical(colnames(get_core("aut"))[1:3], c("country", "pageid", "wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_core("can"))[1:3], c("country", "pageid", "wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_core("cze"))[1:3], c("country", "pageid", "wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_core("esp"))[1:3], c("country", "pageid", "wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_core("fra"))[1:3], c("country", "pageid", "wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_core("deu"))[1:3], c("country", "pageid", "wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_core("irl"))[1:3], c("country", "pageid", "wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_core("sco"))[1:3], c("country", "pageid", "wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_core("gbr"))[1:3], c("country", "pageid", "wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_core("usa_house"))[1:3], c("country", "pageid", "wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_core("usa_senate"))[1:3], c("country", "pageid", "wikidataid"))
  Sys.sleep(1)

  expect_identical(sample(get_core("aut")$country, 1), "AUT")
  Sys.sleep(1)
  expect_identical(sample(get_core("can")$country, 1), "CAN")
  Sys.sleep(1)
  expect_identical(sample(get_core("cze")$country, 1), "CZE")
  Sys.sleep(1)
  expect_identical(sample(get_core("esp")$country, 1), "ESP")
  Sys.sleep(1)
  expect_identical(sample(get_core("fra")$country, 1), "FRA")
  Sys.sleep(1)
  expect_identical(sample(get_core("deu")$country, 1), "DEU")
  Sys.sleep(1)
  expect_identical(sample(get_core("irl")$country, 1), "IRL")
  Sys.sleep(1)
  expect_identical(sample(get_core("sco")$country, 1), "SCO")
  Sys.sleep(1)
  expect_identical(sample(get_core("gbr")$country, 1), "GBR")
  Sys.sleep(1)
  expect_identical(sample(get_core("usa_house")$country, 1), "USA-H")
  Sys.sleep(1)
  expect_identical(sample(get_core("usa_senate")$country, 1), "USA-S")
  Sys.sleep(1)
})

test_that("Political table is returned appropriately for each legislature", {
  skip_on_cran()
  expect_identical(class(get_political("aut")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("can")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("cze")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("esp")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("fra")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("deu")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("irl")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("sco")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("gbr")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("usa_house")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("usa_senate")), "data.frame")
  Sys.sleep(1)

  expect_true(all(dim(get_political("aut")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("can")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("cze")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("esp")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("fra")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("deu")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("irl")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("sco")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("gbr")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("usa_house")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("usa_senate")) > 0))
  Sys.sleep(1)

  expect_identical(colnames(get_political("aut"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("can"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("cze"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("esp"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("fra"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("deu"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("irl"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("sco"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("gbr"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("usa_house"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("usa_senate"))[1], c("pageid"))
  Sys.sleep(1)
})

test_that("Wikipedia History table is returned appropriately for each legislature", {
  skip_on_cran()
  expect_identical(class(get_history("aut")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("can")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("cze")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("esp")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("fra")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("deu")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("irl")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("sco")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("gbr")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("usa_house")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("usa_senate")), "data.frame")
  Sys.sleep(1)

  expect_true(all(dim(get_history("aut")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("can")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("cze")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("esp")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("fra")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("deu")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("irl")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("sco")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("gbr")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("usa_house")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("usa_senate")) > 0))
  Sys.sleep(1)

  expect_identical(colnames(get_history("aut"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("can"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("cze"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("esp"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("fra"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("deu"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("irl"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("sco"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("gbr"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("usa_house"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("usa_senate"))[1], c("pageid"))
  Sys.sleep(1)
})

test_that("Wikipedia Traffic table is returned appropriately for each legislature", {
  skip_on_cran()
  expect_identical(class(get_traffic("aut")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("can")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("cze")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("esp")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("fra")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("deu")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("irl")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("sco")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("gbr")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("usa_house")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("usa_senate")), "data.frame")
  Sys.sleep(1)

  expect_true(all(dim(get_traffic("aut")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("can")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("cze")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("esp")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("fra")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("deu")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("irl")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("sco")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("gbr")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("usa_house")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("usa_senate")) > 0))
  Sys.sleep(1)

  expect_identical(colnames(get_traffic("aut"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("can"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("cze"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("esp"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("fra"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("deu"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("irl"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("sco"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("gbr"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("usa_house"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("usa_senate"))[1], c("pageid"))
  Sys.sleep(1)
})

test_that("Social table is returned appropriately for each legislature", {
  skip_on_cran()
  expect_identical(class(get_social("aut")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_social("can")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_social("cze")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_social("esp")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_social("fra")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_social("deu")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_social("irl")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_social("sco")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_social("gbr")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_social("usa_house")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_social("usa_senate")), "data.frame")
  Sys.sleep(1)

  expect_true(all(dim(get_social("aut")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_social("can")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_social("cze")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_social("esp")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_social("fra")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_social("deu")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_social("irl")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_social("sco")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_social("gbr")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_social("usa_house")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_social("usa_senate")) > 0))
  Sys.sleep(1)

  expect_identical(colnames(get_social("aut"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_social("can"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_social("cze"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_social("esp"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_social("fra"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_social("deu"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_social("irl"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_social("sco"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_social("gbr"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_social("usa_house"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_social("usa_senate"))[1], c("wikidataid"))
  Sys.sleep(1)
})
