test_that("Wikipedia History table is returned appropriately for each legislature", {
  skip_on_cran()
  expect_identical(class(get_history("aut")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("can")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("cze")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("esp")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("fra")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("deu")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("irl")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("sco")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("gbr")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("usa_house")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_history("usa_senate")), "data.frame")
  Sys.sleep(1)

  expect_true(all(dim(get_history("aut")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("can")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("cze")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("esp")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("fra")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("deu")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("irl")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("sco")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("gbr")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("usa_house")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_history("usa_senate")) > 0))
  Sys.sleep(1)

  expect_identical(colnames(get_history("aut"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("can"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("cze"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("esp"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("fra"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("deu"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("irl"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("sco"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("gbr"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("usa_house"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_history("usa_senate"))[1], c("pageid"))
  Sys.sleep(1)
})
