test_that("Political table is returned appropriately for each legislature", {
  skip_on_cran()
  expect_identical(class(get_political("aut")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("can")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("cze")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("esp")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("fra")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("deu")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("irl")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("sco")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("gbr")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("usa_house")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_political("usa_senate")), "data.frame")
  Sys.sleep(1)

  expect_true(all(dim(get_political("aut")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("can")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("cze")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("esp")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("fra")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("deu")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("irl")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("sco")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("gbr")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("usa_house")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_political("usa_senate")) > 0))
  Sys.sleep(1)

  expect_identical(colnames(get_political("aut"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("can"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("cze"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("esp"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("fra"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("deu"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("irl"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("sco"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("gbr"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("usa_house"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_political("usa_senate"))[1], c("pageid"))
  Sys.sleep(1)
})
