test_that("Portraits table is returned appropriately for each legislature", {
  skip_on_cran()
  expect_identical(class(get_portrait("aut")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_portrait("can")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_portrait("cze")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_portrait("esp")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_portrait("fra")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_portrait("deu")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_portrait("irl")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_portrait("sco")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_portrait("gbr")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_portrait("usa_house")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_portrait("usa_senate")), "data.frame")
  Sys.sleep(100)

  expect_true(all(dim(get_portrait("aut")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_portrait("can")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_portrait("cze")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_portrait("esp")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_portrait("fra")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_portrait("deu")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_portrait("irl")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_portrait("sco")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_portrait("gbr")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_portrait("usa_house")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_portrait("usa_senate")) > 0))
  Sys.sleep(100)

  expect_identical(colnames(get_portrait("aut"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_portrait("can"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_portrait("cze"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_portrait("esp"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_portrait("fra"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_portrait("deu"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_portrait("irl"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_portrait("sco"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_portrait("gbr"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_portrait("usa_house"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_portrait("usa_senate"))[1], c("pageid"))
  Sys.sleep(100)
})
