test_that("Wikipedia Traffic table is returned appropriately for each legislature", {
  skip_on_cran()
  expect_identical(class(get_traffic("aut")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("can")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("cze")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("esp")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("fra")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("deu")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("irl")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("sco")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("gbr")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("usa_house")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_traffic("usa_senate")), "data.frame")
  Sys.sleep(1)

  expect_true(all(dim(get_traffic("aut")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("can")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("cze")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("esp")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("fra")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("deu")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("irl")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("sco")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("gbr")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("usa_house")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_traffic("usa_senate")) > 0))
  Sys.sleep(1)

  expect_identical(colnames(get_traffic("aut"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("can"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("cze"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("esp"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("fra"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("deu"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("irl"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("sco"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("gbr"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("usa_house"))[1], c("pageid"))
  Sys.sleep(1)
  expect_identical(colnames(get_traffic("usa_senate"))[1], c("pageid"))
  Sys.sleep(1)
})
