test_that("Offices table is returned appropriately for each legislature", {
  skip_on_cran()
  expect_identical(class(get_office("aut")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_office("can")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_office("cze")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_office("esp")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_office("fra")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_office("deu")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_office("irl")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_office("sco")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_office("gbr")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_office("usa_house")), "data.frame")
  Sys.sleep(1)
  expect_identical(class(get_office("usa_senate")), "data.frame")
  Sys.sleep(100)

  expect_true(all(dim(get_office("aut")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_office("can")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_office("cze")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_office("esp")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_office("fra")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_office("deu")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_office("irl")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_office("sco")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_office("gbr")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_office("usa_house")) > 0))
  Sys.sleep(1)
  expect_true(all(dim(get_office("usa_senate")) > 0))
  Sys.sleep(100)

  expect_identical(colnames(get_office("aut"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_office("can"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_office("cze"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_office("esp"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_office("fra"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_office("deu"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_office("irl"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_office("sco"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_office("gbr"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_office("usa_house"))[1], c("wikidataid"))
  Sys.sleep(1)
  expect_identical(colnames(get_office("usa_senate"))[1], c("wikidataid"))
  Sys.sleep(100)
})
